// <auto-generated />
using System;
using Microservicio_ConsultasMedicas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Microservicio_ConsultasMedicas.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250416133958_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microservicio_ConsultasMedicas.Models.ConsultasMedicasEntity", b =>
                {
                    b.Property<int>("id_consulta_medica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("diagnostico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("fecha")
                        .HasColumnType("date");

                    b.Property<string>("hora")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("id_empleado")
                        .HasColumnType("int");

                    b.Property<string>("motivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("pacienteid_paciente")
                        .HasColumnType("int");

                    b.Property<string>("tratamiento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_consulta_medica");

                    b.HasIndex("pacienteid_paciente");

                    b.ToTable("ConsultasMedicas");
                });

            modelBuilder.Entity("Microservicio_ConsultasMedicas.Models.Paciente", b =>
                {
                    b.Property<int>("id_paciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cedula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("fecha_nacimiento")
                        .HasColumnType("date");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_paciente");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("Microservicio_ConsultasMedicas.Models.ConsultasMedicasEntity", b =>
                {
                    b.HasOne("Microservicio_ConsultasMedicas.Models.Paciente", "paciente")
                        .WithMany()
                        .HasForeignKey("pacienteid_paciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
