// <auto-generated />
using System;
using Microservicio_Administracion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Microservicio_Administracion.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250414234139_consultas")]
    partial class consultas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microservicio_Administracion.Models.ConsultasMedicas", b =>
                {
                    b.Property<int>("id_consulta_medica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("diagnostico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("empleadoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("fecha")
                        .HasColumnType("date");

                    b.Property<string>("hora")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("id_empleado")
                        .HasColumnType("int");

                    b.Property<int>("id_paciente")
                        .HasColumnType("int");

                    b.Property<string>("motivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("pacienteid_paciente")
                        .HasColumnType("int");

                    b.Property<string>("tratamiento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_consulta_medica");

                    b.HasIndex("empleadoId");

                    b.HasIndex("pacienteid_paciente");

                    b.ToTable("ConsultasMedicas");
                });

            modelBuilder.Entity("Microservicio_Administracion.Protos.Centro_Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Centro_Medico");
                });

            modelBuilder.Entity("Microservicio_Administracion.Protos.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cedula")
                        .HasColumnType("longtext");

                    b.Property<int>("CentroMedicoID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<int>("EspecialidadID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<double>("Salario")
                        .HasColumnType("double");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.Property<int>("TipoEmpleadoID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CentroMedicoID");

                    b.HasIndex("EspecialidadID");

                    b.HasIndex("TipoEmpleadoID");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("Microservicio_Administracion.Protos.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Especialidad_")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Especialidad");
                });

            modelBuilder.Entity("Microservicio_Administracion.Protos.Tipo_Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tipo_Empleado");
                });

            modelBuilder.Entity("Microservicio_ConsultasMedicas.Models.Paciente", b =>
                {
                    b.Property<int>("id_paciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cedula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("fecha_nacimiento")
                        .HasColumnType("date");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_paciente");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("Microservicio_Administracion.Models.ConsultasMedicas", b =>
                {
                    b.HasOne("Microservicio_Administracion.Protos.Empleado", "empleado")
                        .WithMany()
                        .HasForeignKey("empleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microservicio_ConsultasMedicas.Models.Paciente", "paciente")
                        .WithMany()
                        .HasForeignKey("pacienteid_paciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("empleado");

                    b.Navigation("paciente");
                });

            modelBuilder.Entity("Microservicio_Administracion.Protos.Empleado", b =>
                {
                    b.HasOne("Microservicio_Administracion.Protos.Centro_Medico", "CentroMedico")
                        .WithMany()
                        .HasForeignKey("CentroMedicoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microservicio_Administracion.Protos.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microservicio_Administracion.Protos.Tipo_Empleado", "TipoEmpleado")
                        .WithMany()
                        .HasForeignKey("TipoEmpleadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentroMedico");

                    b.Navigation("Especialidad");

                    b.Navigation("TipoEmpleado");
                });
#pragma warning restore 612, 618
        }
    }
}
